# config/packages/nelmio_api_doc.yaml
nelmio_api_doc:
    documentation:
        info:
            title: 'Product API'
            description: 'API pour gérer les produits'
            version: '1.0.0'
        media_types:
            json: [ 'application/json' ]
            yaml: [ 'application/yaml' ]   
        paths:
            /api/products
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
            schemas:
                Product:
                    type: object
                    properties:
                        id:
                            type: integer
                            example: 1
                        code:
                            type: string
                            example: "P001"
                        name:
                            type: string
                            example: "Produit 1"
                        description:
                            type: string
                            example: "Description du produit"
                        image:
                            type: string
                            example: "image1.jpg"
                        category:
                            type: string
                            example: "Catégorie 1"
                        price:
                            type: number
                            format: float
                            example: 19.99
                        quantity:
                            type: integer
                            example: 10
                        internalReference:
                            type: string
                            example: "REF001"
                        shellId:
                            type: integer
                            example: 1
                        inventoryStatus:
                            type: string
                            example: "INSTOCK"
                        rating:
                            type: integer
                            example: 5
                        createdAt:
                            type: string
                            format: date-time
                            example: "2024-01-01T10:00:00Z"
                        updatedAt:
                            type: string
                            format: date-time
                            nullable: true
                            example: "2024-01-02T12:00:00Z"

